default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make install'
	@echo
	@echo '	$$ make remove'
	@echo

.PHONY: help


install: install-xftt install-xfted install-xftvim install-xftmicro install-xftkak install-xftnano install-xftne install-xftemacs install-xftmced install-xftlvim

.PHONY: install


remove: remove-xftt remove-xfted remove-xftvim remove-xftmicro remove-xftkak remove-xftnano remove-xftne remove-xftemacs remove-xftmced remove-xftlvim

.PHONY: remove


install-xftt:
	make -C xftt install
.PHONY: install-xftt

remove-xftt:
	make -C xftt remove
.PHONY: remove-xftt


install-xfted:
	make -C xfted install
.PHONY: install-xfted

remove-xfted:
	make -C xfted remove
.PHONY: remove-xfted


install-xftvim:
	make -C xftvim install
.PHONY: install-xftvim

remove-xftvim:
	make -C xftvim remove
.PHONY: remove-xftvim


install-xftmicro:
	make -C xftmicro install
.PHONY: install-xftmicro

remove-xftmicro:
	make -C xftmicro remove
.PHONY: remove-xftmicro


install-xftkak:
	make -C xftkak install
.PHONY: install-xftkak

remove-xftkak:
	make -C xftkak remove
.PHONY: remove-xftkak


install-xftnano:
	make -C xftnano install
.PHONY: install-xftnano

remove-xftnano:
	make -C xftnano remove
.PHONY: remove-xftnano


install-xftne:
	make -C xftne install
.PHONY: install-xftne

remove-xftne:
	make -C xftne remove
.PHONY: remove-xftne


install-xftemacs:
	make -C xftemacs install
.PHONY: install-xftemacs

remove-xftemacs:
	make -C xftemacs remove
.PHONY: remove-xftemacs


install-xftmced:
	make -C xftmced install
.PHONY: install-xftmced

remove-xftmced:
	make -C xftmced remove
.PHONY: remove-xftmced


install-xftlvim:
	make -C xftlvim install
.PHONY: install-xftlvim

remove-xftlvim:
	make -C xftlvim remove
.PHONY: remove-xftlvim
